name: build and Deploye
on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v2

            
            - name: Docker login
              uses: docker/login-action@v2
              with:
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_PASSWORD}}

            - name: Build and push frontend image
              uses: docker/build-push-action@v4
              with:
                context: ./frontendAiInterview
                file: ./frontendAiInterview/Dockerfile
                push: true
                tags: 
                    ${{secrets.DOCKERHUB_USERNAME}}/ai-interview-frontend:${{github.sha}}
                    ${{ secrets.DOCKERHUB_USERNAME }}/ai-interview-frontend:latest

            - name: Build and push backend image
              uses: docker/build-push-action@v4
              with:
                context: ./backendAiInterview
                file: ./backendAiInterview/Dockerfile
                push: true
                tags: 
                    ${{secrets.DOCKERHUB_USERNAME}}/ai-interview-backend:${{github.sha}}
                    ${{ secrets.DOCKERHUB_USERNAME }}/ai-interview-backend:latest